name: getx_annotation
description: getx_gen annotation
version: 0.0.1
homepage: https://github.com/sersr/getx_annotation

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_lints: ^1.0.1
  test: any